name: Build Foo PR
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    name: Build foo
    runs-on: ubuntu-latest
    steps:
      - name: Print Stuff
        run: |
          echo sha=${{ github.sha }}
          echo ref=${{ github.ref }}
          echo head_ref=${{ github.head_ref }}
          echo base_ref=${{ github.base_ref }}
          
      - name: Checkout Source
        uses: actions/checkout@v1
        with:
          ref: ${{ github.sha }}

      - name: Squash Source
        id: squash
        run: |
          git checkout master
          git merge --squash ${{ github.sha }}
          echo "::set-output name=sha::$(git rev-parse HEAD)"
        
      - name: Build
        uses: github-actions-test/cmake-build-action@master
        id: build
        
      - name: Upload artifacts
        run: |
          export dir=${{steps.build.outputs.artifacts}}
          export sha=${{steps.squash.outputs.sha}}
          tar -ca -C ${dir} -f ${sha}.tar.gz .
          curl -Ffile=@${sha}.tar.gz http://35.228.224.98/upload?token=29c0640d89c6f3ecd256
