name: Build Foo PR
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    name: Build foo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
        
      - name: Build
        uses: github-actions-test/cmake-build-action@master
        id: build
        
      - name: Cache Artifacts
        uses: actions/cache@v1
        with:
          path: ${{ steps.build.outputs.artifacts }}
