name: Build Foo PR
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    name: Build foo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
        
      - name: Build
        uses: github-actions-test/cmake-build-action@master
        id: build
        
      - name: Upload artifacts
        run: |
          tar -ca -C ${{steps.build.outputs.artifacts}} -f ${{github.sha}}.tar.gz .
          curl -Ffile=@${{github.sha}}.tar.gz http://35.228.224.98/upload?token=29c0640d89c6f3ecd256
