name: Merge Foo PR
on:
  pull_request:
    types: [closed]
jobs:
  build:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meta Repository
        uses: actions/checkout@v1
        if: github.event.pull_request.merged == true
        with:
          repository: github-actions-test/actions
          ref: master
          
      - name: Update Ref to ${{ github.repository }}
        if: github.event.pull_request.merged == true
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          set -eEuo pipefail
          set -x
          pwd
          ls
          cd ../actions
          git submodule init foo
          git submodule update foo
          (cd foo && git fetch -a && git checkout $GITHUB_REF)
          git add foo
          git commit -m'Update foo'
          git push
          
