name: Merge Foo PR
on:
  pull_request:
    types: [closed]
jobs:
  build:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meta Repository
        uses: actions/checkout@v1
        if: github.event.pull_request.merged == true
        with:
          repository: github-actions-test/actions
          ref: master

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Update Ref to ${{ github.repository }}
        if: github.event.pull_request.merged == true
        run: |
          set -eEuo pipefail
          export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          cd ../actions
          git config --global user.email 'actions@github.com'
          git config --global user.name 'GitHub Actions'
          git submodule init foo
          git submodule update foo
          (cd foo && git fetch -a && git checkout $GITHUB_REF)
          git add foo
          git commit -m'Update foo'
          git push
          
