name: Merge Foo PR
on:
  pull_request:
    types: [closed]
jobs:
  build:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH Agent
        if: github.event.pull_request.merged == true        
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Checkout Meta Repository
        if: github.event.pull_request.merged == true
        run: |
          set -eEuo pipefail
          set -x
          export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          git clone git@github.com:github-actions-test/actions.git
          
      - name: Update Ref to ${{ github.repository }}
        if: github.event.pull_request.merged == true
        run: |
          set -eEuo pipefail
          set -x
          export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

          # Check out the meta repository so that we can make changes in it based on this pull request merge
          cd actions
          git config --global user.email 'actions@github.com'
          git config --global user.name 'GitHub Actions'
          git submodule init foo
          git submodule update foo
          cd foo
          git fetch -a
          git checkout master

          # Promote the uploaded pull request binary to represent master
          export pr=$(git log -1 --pretty=%B | sed -E 's/.+#([0-9]+).+/\1/g')
          curl --fail -s -o foo-master.tar.gz       http://35.228.224.98/files/foo-pr-${pr}.tar.gz?token=29c0640d89c6f3ecd256
          curl --fail -s -F file=@foo-master.tar.gz http://35.228.224.98/upload?token=29c0640d89c6f3ecd256)

          # Update the meta repository with the current foo master
          git add foo
          git commit -m'Update foo'
          git push
          
