name: Foo PR
on: [pull_request]
jobs:
  build:
    name: Build foo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: github-actions-test/cmake-build-action@master
        with:
          uploadUrlPattern: 'http://35.228.224.98/upload?token=29c0640d89c6f3ecd256'
